name: api

on:
  push:
    branches: [main]
    paths:
      - 'Backend/src/Api/**'
      - 'Backend/test/Api/**'
      - '.github/workflows/api-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'Backend/src/Api/**'
      - 'Backend/test/Api/**'
      - '.github/workflows/api-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore Backend/src/Api/taskFlow.Api/taskFlow.Api.csproj

      - name: Build
        run: dotnet build Backend/src/Api/taskFlow.Api/taskFlow.Api.csproj --no-restore --configuration Release
  
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore Backend/test/Api/taskFlow.Api.tests/taskFlow.Api.tests.csproj

      - name: Test
        run: dotnet test Backend/test/Api/taskFlow.Api.tests/taskFlow.Api.tests.csproj